### ISSUE TITLE
Qt interface has no unit tests

### ISSUE THREAD

**Issue by aleixpol** [ximion/appstream#10]
Having some tests for generating and querying the database are needed in order to figure out when we regress.

**Comment by ximion** [comment]
We do have unit-tests for the database and parsing - having more would be much better, of course ;-)

Only the Qt interface doesn't have tests right now, mainly bacause adding some would mean that compiling the Qt interface independently from the rest of AppStream wouldn't be possible anymore, and that's something svuorela wanted back in the days.
(background is that the tests would need to ensure that a temporary database for testing is generated using the latest AppStream (libappstream) code, and therefore would have to call the recently compiled appstreamcli tool)
Since nobody currently compiles the Qt interface without also having the command-line tools, adding a (test-only) dependency here would be fine with me, but I'd have to ask svuorela first.

**Comment by aleixpol** [comment]
So they aren't integrated in cmake? "ctest ." gives nothing.

**Comment by ximion** [comment]
They should be.... I run "make test" frequently without issues... Maybe cmake wants more than just add_test to be called for proper ctest integration?

**Comment by aleixpol** [comment]
Tests are disabled by default, I didn't realize that. Sorry.

**Comment by ximion** [comment]
Aaah :-)
Well, this is something that should be mentioned on the README ;-)
(Also, I think enabling the tests by default doesn't hurt)

**Comment by ximion** [comment]
We now have a very simple unit-test for Qt - needs to be extended, of course.
I am closing this report, since higher test coverage is a general goal, and the particular issue here has been resolved (tests are now documented, and also enabled by default).
