### ISSUE TITLE
Make GIR optional?

### ISSUE THREAD

**Issue by eternaleye** [ximion/appstream#139]
Currently, the GObject Introspection support is hard-enabled. However, g-ir-scanner is rather painful for cross-compilation, and isn't needed for any of the things I need appstream for (Plasma Discover, in particular).

I tried brute-force hacking out the gir compilation from `src/meson.build`, and the result worked perfectly. Could this be put behind an option, which the vala option requires?

**Comment by ximion** [comment]
Weird, my reply from weeks ago has vanished...
I wrote previously that I am usually against disabling such things, since it increases the amount of configurations to test and GIR is a very useful feature (and disabling it has a chance of language bindings getting out of sync).
However, cross-compilation is a good reason to want this functionality, and I know that GIR is pretty annoying in that particular scenario, especially if you just want to test something quickly.
So, I added an option to disable the generation of introspection data, and hope most people will never touch it ;-)

Cheers!
