### ISSUE TITLE
Where I can check is application appstream compatiable

### ISSUE THREAD

**Issue by igorSmirnovPlexi** [ximion/appstream#149]
Hi, how can I find is application supports appstream. Especially applications like mongodb, oracledb, sap hana. If they don't support, is appstream-generator able to generate appstream metadata for them?

**Comment by ximion** [comment]
> If they don't support, is appstream-generator able to generate appstream metadata for them?

No, unless a .desktop file in `/usr/share/applications/` is available for a GUI app.

> how can I find is application supports appstream

They need to install a [metainfo file](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html) into `/usr/share/metainfo/` in order to be recognized. The projects you listed would mostly require a metainfo file describing a `service` or `console-application` component.

Maybe at some point we could add support to asgen to allow injecting metadata snippets from random sources, but at the moment I really want to avoid that as it makes people not fix the actual issues. Ideally file a bug/patch to MongoDB & Co. to include a metainfo file (might be a lot trickier for SAP/Oracle things).
