### ISSUE TITLE
Consider discouraging/prohibiting the use of hyphens in Appstream IDs, to match the DBus spec

### ISSUE THREAD

**Issue by Pointedstick** [ximion/appstream#162]
Right now AppStream recommends reverse-DNS-style IDs and supports the full range of rDNS characters, including hyphens anywhere (e.g. `com.my-awesome-website.my-awesome-app`).

However, DBus does _not_, and [discourages the use of hyphens anywhere but the last element](https://cgit.freedesktop.org/dbus/dbus/tree/doc/dbus-specification.xml#n1835). So to be valid to DBus, that string would have to be `com.my_awesome_website.my-awesome-app` or `com.myawesomewebsite.my-awesome-app`.

This has caused a situation where the FileZilla developers [adopted an AppStream ID](https://trac.filezilla-project.org/ticket/11478#comment:6) with a hyphen in the middle (`org.filezilla-project.FileZilla`) that complies with the AppStream spec, but not the DBus spec. When I asked them to change their ID to remove the hyphen, they pointed out quite reasonably that it was a perfectly valid AppStream ID.

We might consider changing the AppStream spec for IDs to match the DBus spec and discourage or prohibit the use of hyphens anywhere but the last element to prevent this kind of confusion.

**Comment by smcv** [comment]
The D-Bus specification discourages hyphens everywhere, not just in the non-last components.

The Flatpak specification is the one that has a problem with hyphens in non-last elements. It forbids hyphens anywhere except the last element for some technical reason that I don't fully understand: I think it's something to do with wanting an app to be able to "export" multiple icons (`com.example.App.png` and `com.example.App-symbolic.png`) while guaranteeing an absence of collisions with other apps, although I'm not entirely sure how the restriction avoids the collisions.

**Comment by ximion** [comment]
Yes, I agree with this as said in the discussion on the mailinglist. I just haven't had time to implement the result of that discussion, due to finishing a thesis and then a lot of other stuff happened too.
In any case, I hope I can make the necessary changes soon.

I will not make hyphens in IDs an error from the AppStream side (at least not for now), but I will add a warning to the specification and guides about this issue, and make `appstreamcli validate` throw out an info-type hint to notify about this, so people can fix their component-IDs.

**Comment by Pointedstick** [comment]
Awesome, thanks folks.

**Comment by smcv** [comment]
> to be valid to DBus, that string would have to be `com.my_awesome_website.my-awesome-app`

This is allowed but not recommended. `com.my_awesome_website.my_awesome_app` (or more conventionally, `com.my_awesome_website.MyAwesomeApp`) is preferred.

> or `com.myawesomewebsite.my-awesome-app`

That's not valid, because the owner of my-awesome-website.com typically does not also own myawesomewebsite.com, so they have no way to know that the owner of myawesomewebsite.com won't release a different app with that name. Curated app-stores like Flathub should reject app IDs that are based on a domain not owned by the app's publisher.

**Comment by Pointedstick** [comment]
This all came about because Flathub has taken the liberty of assigning Appstream IDs to certain apps that did not already provide them. [One such example is FileZilla](https://github.com/flathub/org.filezillaproject.Filezilla/pull/1), which was assigned `org.filezillaproject.Filezilla`. I gather this is incorrect because `filezillaproject` != `filezilla-project` and should have been `filezilla_project`?

Either way, now Flathub uses `org.filezillaproject.Filezilla` and the FileZilla people use `org.filezilla-project.FileZilla` and this is a mess and I'm trying to figure out what to do about it.

**Comment by smcv** [comment]
> One such example is FileZilla, which was assigned `org.filezillaproject.Filezilla`. I gather this is incorrect because `filezillaproject` != `filezilla-project` and should have been `filezilla_project`?

Yes, Flathub was wrong to apply that transformation. Nobody can own `filezilla_project.org` because underscores aren't allowed in domain names, so it can't possibly collide with a real domain name, which is why normalizing/escaping `filezilla-project` to `filezilla_project` is an OK thing to do. (Similarly, nobody can own `_7_zip.org` because domain name components can't start with underscores, so it's OK to escape `7-zip` as `_7_zip`, which is the example I like to use in places like the D-Bus Specification.)
