### ISSUE TITLE
 AND/OR not parsed correctly for metadata_license

### ISSUE THREAD

**Issue by jbicha** [ximion/appstream#181]
I guess I filed https://github.com/hughsie/appstream-glib/issues/226 in the wrong place since my bug was specifically about `appstreamcli`.

I'll go ahead and copy what I posted there…

The aisleriot and gnome-terminal developer now uses this license in his [AppStream metadata](https://git.gnome.org/browse/gnome-terminal/tree/org.gnome.Terminal.appdata.xml.in):

```<metadata_license>GPL-3.0+ or GFDL-1.3-only</metadata_license>```

GFDL-1.3-only is SPDX 3.0 syntax (see https://github.com/ximion/appstream/issues/180 )

But even if we change it to `GPL-3.0+ or GFDL-1.3`, `appstreamcli validate` complains that the metadata does not use a valid permissive license. For Debian and Ubuntu, I had to use a patch to drop the `GPL-3.0+ or ` so that the app will show up in the GNOME Software app.

Substituting _and_ doesn't work here either.  _or_ is the correct intent of the developer and should be sufficient for AppStream's concerns but _and_ would not be acceptable here.

References
----------------
Appendix IV:  SPDX License Expressions of https://spdx.org/specifications

**Comment by ximion** [comment]
I think back then I intentionally did only allow SPDX license codes, and not license expressions for this tag, to keep the ambiguity low (and because I thought nobody would even bother to put an expression there.
The specification says at https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#sect-Metadata-GenericComponent
> The license codes correspond to the identifiers found at the SPDX OpenSource License Registry.

Which admittedly isn't incredibly clear.
That being said, I am not very against supporting expressions there.
@hughsie what do you think, should we do that? (In any case I would clarify the wording in the spec)

OT: gnome-terminal as far as I remember, has always been an odd case, since AFAIR its maintainer refused to put the metadata under any license that was not the license of the software itself. Hence it was GPL only before and excluded from metadata collections.

**Comment by ximion** [comment]
Ah, it looks like Richard already fixed this in his code. I will likely do the same in that case.

**Comment by jbicha** [comment]
Yes, this was a recent breakthrough for gnome-terminal and a few projects under similar maintainership.

I've not seen this licensing anywhere else (well, it didn't work so that's one very good reason!)
