### ISSUE TITLE
Add citable references

### ISSUE THREAD

**Issue by daissi** [ximion/appstream#190]
Hi,
So, now the bug is open :-)

Maybe we can start the discussion with a minimal example:

```
<bibliography>
  <title>GWAMA: software for genome-wide association meta-analysis</title>
  <authors>Reedik Mägi and Andrew P. Morris</authors>
  <date>2010/05/28</date>
  <journal>BMC Bioinformatics</journal>
  <doi>10.1186/1471-2105-11-288</doi>
</bibliography>
```

What do you think about this?

**Comment by ximion** [comment]
I actually had something even more basic in mind back then:
```xml
<bibliography>
    <citation doi="10.1186/1471-2105-11-288">
        Mägi, R. &amp; Morris, A. P. GWAMA: software for genome-wide association meta-analysis. BMC Bioinformatics 11, 288 (2010).
    </citation>
</bibliography>
```
What I would like to avoid is having a full-blown BibTeX like reference database in AppStream.

@hughsie @aleixpol What do you think? For a UI having the data neatly split into author/date/journal etc. would be nice, I guess. Question is whether AppStream is the right place to store this information in such detail.
In case we want this, and we want details, I would favor something like this:
```xml
<bibliography>
    <citation doi="10.1186/1471-2105-11-288">
        <title>GWAMA: software for genome-wide association meta-analysis</title>
        <authors>Reedik Mägi, Andrew P. Morris</authors>
        <date>2010-05-28</date>
        <journal>BMC Bioinformatics</journal>
    </citation>
</bibliography>
```

With `date` being an ISO 8601 date, `authors` being a simple string with authors ideally being comma-separated (instead of making an `authors` root node with the individual authors listed as child nodes) and the DOI as citation identifier.

**Comment by hughsie** [comment]
> What do you think?

I don't think this is something that we'd show in a software center, and thus doesn't belong in AppStream. Sorry.

**Comment by ximion** [comment]
@hughsie From being in science myself, I know that people will actually (try to) search for that in software centers, and it might be a useful feature for dedicated tools to display the right software for a publication. At least the former would make it relevant for AppStream because it falls in the "information relevant to the user to decide whether they want to install the application" category that I use to determine what belongs into AS.

However admittedly this is a fringe feature that's useful for a really small amount of people, and AppStream really isn't the right place for a bibliography reference list. So, I really haven't made up my mind on this yet (which is why when this was originally requested on the mailinglist the discussion kind of faded, so I'm glad that we have an open ticket for this now).

**Comment by hughsie** [comment]
If they're searching for it, it's a <keyword> surely?

**Comment by ximion** [comment]
@hughsie A "surely" for adding that feature?

**Comment by hughsie** [comment]
Gahh sorry, my phone ate the formatting. I meant "it's a `<keyword>` surely"

**Comment by ximion** [comment]
I was looking into this again, and I think for citing software CITATION.cff is a much better solution: https://citation-file-format.github.io/
It is complete and machine-readable. Overloading AppStream with this is probably not a great idea.

However, using online databases, we can generate citations for anything that has a DOI.
So, what would definitely work and may be a good idea is if we encode the DOI in an AppStream MetaInfo file.
That way, any library management software like Zotero or Endnote could generate the required citation in the right style,
or software tools could send the DOI to a service like Crosscite (https://citation.crosscite.org/) to get the citation formatted. Or, we could just jump to the document describing the software via doi.org and go from there.

@daissi, what do you think?
