### ISSUE TITLE
Provide different DPI for the icons

### ISSUE THREAD

**Issue by tintou** [ximion/appstream#21]
Currently the specification doesn't mention anything related to DPI support.
It seems that people are wrongly using the 128px icons for the 64@2 icons but they are not the same icons.
Here are more explicit informations about this problem:
http://blog.elementary.io/post/124193007916/whats-up-with-hidpi-icons
To solve this problem i propose to allow a dpi property that way:

``` xml
<icon type="remote" width="64" height="64">http://example.com/icons/foobar.png</icon>
<icon type="remote" width="64" height="64" dpi="2">http://example.com/icons/foobar@2.png</icon>
```

The default dpi value should be 1 so it's not mandatory to set it.

**Comment by ximion** [comment]
We can probably have that with a `scale` property instead of `dpi` - but I don't know whether distributions would actually ship icons for `64x64`, `64x64@2` and `128x128`.
I could imagine for Debian to drop `128x128` and just ship the `64x64` icons and the scaled ones.
Downloading them in all sizes it quite a huge amount of data.

**Comment by ximion** [comment]
Looks like KDE Discover will have an interest in this as well, soon.

**Comment by ximion** [comment]
Please keep in mind that this is only part of the solution: The AppStream generator will need support for it too to generate another tarball with HiDPI icons, and to set the proper metadata.
With this, the initial work is done though and adding support to asgen isn't hard (and I plan to have it for the next release of it).
