### ISSUE TITLE
Metainfo licenses: gfdl without invariant

### ISSUE THREAD

**Issue by juanma1980** [ximion/appstream#225]
I think I've found a bug:

> metainfo-license-invalid
> The metainfo file does not seem to be licensed under a permissive license. Valid permissive licenses include FSFAP, CC0-1.0 or MIT. Permissive licenses are required to allow distributors to include the metadata in mixed data collections without the risk of license violations due to mutually incompatible licenses. If you think this message is an error and 'GFDL-1.2-without-invariant' is actually valid, please file a bug against AppStream. 
> 

GFDL-1.2-without-invariant mut be ok as GFDL-1.2 is a valid one. Or maybe I'm missing something?

**Comment by ximion** [comment]
That license identifier is not listed in the SPDX license list: https://spdx.org/licenses/ or in the common license exceptions.
I would gladly add this license as allowed, because especially in Debian GFDL with invariant sections is considered non-free, but I think the proper way is to have SPDX include the license ID first.
Unless I am missing something here, of course.

**Comment by juanma1980** [comment]
I see your point, I think you're right. I'll contact package mantainer and ask him to contact spdx or change the metainfo license.

**Comment by ximion** [comment]
Since AppStream supports the SPDX `WITH` operator now, all that would be needed is to add this to the exception list with some common ID: https://spdx.org/licenses/exceptions-index.html

**Comment by ximion** [comment]
Actually, I don't think we'll be adding more permitted licenses to the metainfo license set. Otherwise @hughsie will go mad, but also if we do that we will basically be adding new licenses forever to the permitted list and have lawyers perpetually reviewing them.
Does `FSFAP` as license work for you in this case?
