### ISSUE TITLE
Proposing a new URL type: downloadpage

### ISSUE THREAD

**Issue by probonopd** [ximion/appstream#232]
I am proposing a new URL type: `downloadpage`.

Rationale:
Sites like https://appimage.github.io/ may want to link to a project's download page, not just the homepage. Currently there is no way to do that using the AppStream metainfo.

**Comment by ximion** [comment]
I still would much rather want to add a way to do a trusted and verified download automatically, instead of linking the user to some random page on the internet where they would have to search for a way to download some random executable.
I'd consider adding such a URL an antifeature.
I would be open to adding a way to automatically fetch these things, e.g. by using the new [release artifacts](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-releases).

**Comment by ximion** [comment]
This is being discussed at https://github.com/ximion/appstream/issues/154 already as well.
