### ISSUE TITLE
AppStream Button

### ISSUE THREAD

**Issue by aleixpol** [ximion/appstream#24]
Some time ago we started discussing about the appstream://id scheme.

Then I discussed with our Visual Design Group that it might be interesting to have a button that we can use to indicate that a button leads to an AppStream URI (from a website, although it might make sense on applications as well).

Here's what @Ken-Vermette came up with, and I think it's an interesting approach:
https://share.kde.org/index.php/s/MPpOOEl7JpGAWzu/download

Do you think it would make sense?

**Comment by ximion** [comment]
Mandating or recommending it in the spec IMHO doesn't make sense, as things like that don't belong there.
However, we do have a quickstart guide in there and some other documentation. Adding something like that to these pages makes a lot of sense, since it will make this feature known to app developers and also give them a way to immediately add it to their websites with a fancy button.
So, +1 from me on that. I also like the button design - should the button text be something like "Install app in software center", to make it obvious to people what it does?
The term "AppStream" is probably only known to a few people.

**Comment by aleixpol** [comment]
> Mandating or recommending it in the spec IMHO doesn't make sense, as things like that don't belong there.

Why not? I mean, it's not about mandating, because it's not about enforcing but facilitating. If it's not easy, it won't be used at all. A good way to facilitate is by having the Appstream project actively suggest it.

**Comment by ximion** [comment]
It's not really in-scope as part of the specification of AppStream metadata - but as said, making the project suggest it would make a lot of sense.

**Comment by ximion** [comment]
When you have a final design, let me know, so I can include it in the docs!

**Comment by ximion** [comment]
Ping on this one - do we have something ready to ship?

**Comment by Ken-Vermette** [comment]
Final design attached;

[appstream.zip](https://github.com/ximion/appstream/files/453438/appstream.zip)

**Comment by ximion** [comment]
Added as https://github.com/ximion/appstream/commit/0aa623a1dcae7af88a99d49d2b8b8552bcd4d19a - thank you :-)
