### ISSUE TITLE
Allow WebP as a screenshot format

### ISSUE THREAD

**Issue by chungy** [ximion/appstream#252]
in the specification, JPEG and PNG are allowed for screenshots, but this seems a little constraining now. Since Firefox and Chromium both support WebP (and most of GNOME does, too), it is a pretty appealing image format that can compress better than either of the other two in lossy and lossless modes both.

I would like to start moving web sites over to WebP-only, but the screenshots in the AppStream specification requiring me to use PNG is constraining to this goal.

**Comment by ximion** [comment]
Aktually the specification permits on PNG as output format, so if collection XML/YAML is generated, all screenshot images are converted from whatever format they were in before to PNG, and I would actually like to keep it that way unless there is a string reason to allow a different format.
However, in metainfo XML files, the things upstream projects write, using PNG/JPEG is permitted, and there I think allowing WebP as well wouldn't be a bad idea, as long as it is supported ubiquitously.
@hughsie , what do you think? @aleixpol , since these images may end up being served to software centers directly, without being converted to PNG, on distributions like Arch: Do you see any problems with Discover displaying WebP? (I don't know how well Qt supports this, but I guess it does)

**Comment by hughsie** [comment]
.png needs to be the output format, but I have no problem in specifying it as a source format
