### ISSUE TITLE
Alert in Weblate

### ISSUE THREAD

**Issue by rffontenelle** [ximion/appstream#260]
There seems to be some kind of file conflict, according to https://hosted.weblate.org/projects/appstream/translations/#alerts. I don't know if it is still blocking translations at Weblate from being merged, but all I know is I translated to 100% in a month and it didn't hit the repository. Could this please be verified?

**Comment by ximion** [comment]
Thanks for filing this issue, I didn't notice the problem.
Very weird that Weblate got confused, force-pushing is disabled for this repository, so there should be no changes that Weblate can't handle.
Maybe the last l10n template update confused it somehow....

In any case, the issue is resolved now and everything should work fine again! I was wondering why no translations were coming in, and well, that was the reason.

**Comment by ximion** [comment]
Hmm, the translation status doesn't show as 100%... I didn't check it before though, I really hope Weblate didn't just forget localization data when rebasing the respository.

**Comment by rffontenelle** [comment]
@ximion That's weird. Did you follow the "tipical instructions" (or named similarly) below the actual Git error message in the Alert page? Theoretically it should not lose the localization data so far. But it is ok, just a little rework (at least to pt_BR)
