### ISSUE TITLE
Make it possible to fall back to other languages

### ISSUE THREAD

**Issue by aleixpol** [ximion/appstream#293]
Much like we do in UIs, we need to be able to get a different text if the application we're browsing isn't available on our configured language:
https://bugs.kde.org/show_bug.cgi?id=420891

Otherwise we are not very useful on other (minoritary?) languages.

**Comment by ximion** [comment]
We already do that fallback, however, if a translator has translated any part of the description text, we show what we got and deliberately don't produce a half-English half-translated mix of a text.
In the linked case, unfortunately, a translator translated a tiny part of the description, yielding this result. I wonder whether we should add a rule like "first paragraph has to be translated", and if it isn't, completely fall back to the English text.

**Comment by ximion** [comment]
This "first paragraph needs translation" is actually not possible to implement - AppStream has no idea what the "first paragraph" is when iterating through all `p`/`li` elements, and it will just show all of them into the respective locale buckets. There is no programmatic way to test whether a paragraph was translated.

I could of course implement some rule that "more than one paragraph needs to be translated", but some translations only *have* one paragraph. Also, potentially that paragraph is long enough so that it is actually a meaningful translation and should actually show up instead of being thrown out.

So, at the moment I see no way to fix this, as AppStream doesn't (and can't) understand whether the text it displays has meaning, and any "you must have X amount of translated text" rule will certainly produce regressions. Better heuristics would depend on translations being in the right order, which is also nothing we can assume is the case, and doing so may break other usecases.

 So, I think this is really a matter for the toolchain that *has* all the information that AppStream doesn't have once the final XML data is generated: The KDE translation tools. Those could simply prevent translating the XML if a certain language localizes less than 40% of the application's metadata, thereby causing English text to be shown to the user.

**Comment by ximion** [comment]
I've implemented a workaround for this which should definitely address some of the more extreme cases. For the fine tuning, upstream projects will really have to do the work though to ensure their translations are sane.
