### ISSUE TITLE
/usr/share/metainfo/<ID>.metainfo.xml backwards compatibility

### ISSUE THREAD

**Issue by eszlari** [ximion/appstream#294]
AFAIK the historical progression of the standard location of an appstream data file for a regular desktop app is as follows:

1. `/usr/share/appdata/<ID>.appdata.xml`
2. `/usr/share/metainfo/<ID>.appdata.xml`
3. `/usr/share/metainfo/<ID>.metainfo.xml` (current spec)

What was the first appstream version that supported the current location (3)?

I'm asking to determine which old distros support it and when it's safe for upstream projects to change this in their source trees.

**Comment by tintou** [comment]
The switch to 2. is here: https://github.com/ximion/appstream/commit/0a916605083bb3ceaa3439d0895a9d40fc59f037
At that point, it was already supporting `.metainfo.xml` files.

**Comment by ximion** [comment]
Jup, since AppStream 0.9.4 (since 2016-04-18).
Every LTS distribution, including Debian, Ubuntu (including older ones like18.04 LTS) and AFAIK even RHEL via updates supports this, so it's pretty much safe to be used unconditionally.
In fact, if the AppStream 1.0 release plans had worked out for this year, the support for the old location would have been dropped already.
On my Debian system, `/usr/share/appdata` is empty (only Chrome puts its file in there for some reason), and last time I looked in all of Debian only 42 components of 2262 were using the old location.
So yeah, it's safe to switch. The `.metainfo.xml` suffix is ancient too, but you can stick with the appdata one, most apps did that for desktop-application components anyway, as the "you can use .metainfo.xml for any metadata" recommendation was done later. Also, we'll never deprecate the `.appdata.xml` suffix, unlike the old metadata location.
