### ISSUE TITLE
as-utils from appstream-glib need to be included in appstream

### ISSUE THREAD

**Issue by Conan-Kudo** [ximion/appstream#299]
There are a number of utility functions in appstream-glib that do not exist in appstream, and without them, it'd basically impossible to migrate to libappstream.

* as-utils from appstream-glib: https://github.com/hughsie/appstream-glib/blob/master/libappstream-glib/as-utils.h
* as-utils from appstream: https://github.com/ximion/appstream/blob/master/src/as-utils.h

For example, I cannot migrate PackageKit's libappstream-glib dependency to libappstream because `as_utils_install_filename()` is used in the DNF backend:

https://github.com/hughsie/PackageKit/blob/ed73aa6317595d2c2f1bda7990cbd64efb133f84/backends/dnf/pk-backend-dnf.c#L524-L545

**Comment by ximion** [comment]
I will not blindly add all of as-utils, especially if nothing uses functions from it within AppStream, and also because there are a lot of duplicates.
The function you are referencing only copies a file from a to b though. `appstreamcli` has the same thing with its `put` subcommand.
I will look into adding it, but most likely without the libarchive parts to extract a tarball.

**Comment by Conan-Kudo** [comment]
> I will look into adding it, but most likely without the libarchive parts to extract a tarball.

That's a problem, though, since the icons and such are in a tarball.

**Comment by ximion** [comment]
Well, you could just extract that stuff in dnf. But libappstream also has a vendor-specific function on Debian functions that just calls tar to unpack stuff, maybe that's good enough as well.

**Comment by ximion** [comment]
I added this feature as API function now. I do think that the metadata should be installed and extracted by the package manager explicitly though, rather than using a function that relies on heuristics to determine some of its values.
But since appstreamcli could already do this (although only for metainfo files) there was no reason to not also add an API function for metadata installation.

By the way, @hughsie : Do you really want the appstream-glib variant of this feature creating world-readable directories? ;--)
=> https://github.com/hughsie/appstream-glib/blob/master/libappstream-glib/as-utils.c#L1157

**Comment by Conan-Kudo** [comment]
> I added this feature as API function now. I do think that the metadata should be installed and extracted by the package manager explicitly though, rather than using a function that relies on heuristics to determine some of its values.

There's almost no point in DNF doing it, since it can't really use the data for anything. That's why PackageKit does it instead.
