### ISSUE TITLE
Index third party apps that do not ship as.xml data

### ISSUE THREAD

**Issue by dantti** [ximion/appstream#3]
Use case:
User goes to skype.com, viber.com dowloads their debs, install them, some time later willing to clean up stuff and not a user of skype/viber/chrome/whatever opens the software center and looks for installed apps, it will not be in the applications section.

These debs are not in any local repo and even it they where the provider might change the package name at anytime, we can´t make these companies to provide as.xml data.

My idea would be calling packagekit with getPackages(Application|Installed), and if their packages is not in the index yet index the .desktop files

**Comment by ximion** [comment]
We could add these apps as stub and have the software center figure out the package which owns them via PK `GetFiles()`, since doing calls to the package management system is something I don't want to do when updating the cache - this process should be as fast as possible and should be able to run at any time (even if the package database is locked or being updated).

This solution is really ugly, because it will introduce entries without installation candidate into the AppStream database, which currently does never happen. But this might be a bitter pill to take, if there is strong demand from software center people to add this feature.

**Comment by ximion** [comment]
With the latest changes, we might finally be able to do this...
Problem is: Do we *want* to do this? It will force software-center apps to resolve a filename to packages, which is pretty slow...

**Comment by ximion** [comment]
I think I found a solution for this issue which makes sense (using a configuration option to switch to "show data from metainfo files" mode for developers, and reading .desktop files and metainfo files unconditionally if the distributor does not have any information about them).
Will work on this for a later release (maybe 0.10.2)
