### ISSUE TITLE
Doesn't check some things appstream-util checks

### ISSUE THREAD

**Issue by agx** [ximion/appstream#334]
I had appstreamcli validate a metainfo file but `appstream-util` still spotted missing optional tags:

```
• tag-missing           : <content_rating> required [use https://odrs.gnome.org/oars]
• file-invalid          : <screenshot> failed to load [https://source.puri.sm/guido.gunther/livi/-/blob/main/screenshots/landscape-fullscreen.png]
• tag-missing           : <release> required
```

Would be great if `appstreamcli` would check a superset of `appstream-util` especially since flathub uses `appstream-util` to validate submissions.

**Comment by ximion** [comment]
Those, except for the `file-invalid` one, aren't issues though, so they would at max be info priority things. I don't know if we can spam people to use release tags yet, but for the `content_rating` one we could probably emit a hint for at least GUI applications (not sure about console apps, and it makes no sense for things like firmware).

For the screenshot though: The issue is that the file downloaded isn't actually a PNG image but a HTML page, right? Libappstream can't hard-depend on something like GDK for image loading (due to being lightweight without GUI dependencies and cross-toolkit), but maybe we can work something else out - e.g. test the MIME type of the downloaded image, or test for a PNG magic number explicitly, or at least test for "not HTML text".
