### ISSUE TITLE
`custom` node isn't being exported to collection metadata

### ISSUE THREAD

**Issue by tintou** [ximion/appstream#339]
Per [the collection specification](https://www.freedesktop.org/software/appstream/docs/chap-CollectionData.html), the `custom` node isn't visible, would it make sense to add it there (we are using it in elementary AppCenter to enhance our store).

**Comment by ximion** [comment]
What do you mean with "isn't visible"? Does libappstream not read it when it's present (it should), or is the `custom` entry not present in the source XML? In the latter case, the issue is with your metadata generator, which, in case it's `appstream-generator`, will need a whitelist of allowed custom keys that it should put into the generated XML or YAML.
See `AllowedCustomKeys` in https://github.com/ximion/appstream-generator/blob/master/docs/asgen-config.md#toplevel-fields for reference.

**Comment by tintou** [comment]
Unfortunately, for flatpak that's still libappstream-glib, and it produces a `metadata` entry instead of `custom` (per https://github.com/hughsie/appstream-glib/blob/e98c97fcd4e0ffa17b00f842c9bad462bf7c3afb/libappstream-glib/as-app.c#L4834 ) but that should be fixed by at least increasing the version in https://github.com/hughsie/appstream-glib/pull/407
This bug is more toward the specification that doesn't seem to cover this field, even in the optional case.

**Comment by ximion** [comment]
What do you expect the specification to say about it? Looks like you kind of already found the source of your issue, with a solution for it.
The `custom` tag is, by definition, optional.

**Comment by ximion** [comment]
Closing, as bug is stale.
