### ISSUE TITLE
screenshot URL from appdata is ignored

### ISSUE THREAD

**Issue by nqn76** [ximion/appstream#34]
In org.kde.dolphin.appdata.xml there's
```
  <screenshots>
    <screenshot type="default">
      <image>http://kde.org/images/screenshots/dolphin.png</image>
    </screenshot>
  </screenshots>

```
In the distro appdata database, in the dolphin component:
```
  <screenshots>
    <screenshot type="default"><caption/><image type="source">http://kde.org/images/screenshots/dolphin.png</image></screenshot>
  </screenshots>
```

However, after refreshing the cache:
```
> sudo appstreamcli refresh-index --force
> appstreamcli search dolphin --details
...
Sample Screenshot URL: http://screenshots.debian.net/screenshot/dolphin
...

```

**Comment by ximion** [comment]
Okay, this is actually not a bug...
```
<screenshots>
  <screenshot type="default">
    <image type="source">http://kde.org/images/screenshots/dolphin.png</image>
  </screenshot>
</screenshots>
```
This screenshot has no width/height, and since screenshots without width/height are forbidden in Distro-XML, it gets ignored.
This happens by running the generator with `handleScreenshots` set to `false`. Maybe that option needs to be split into two, one for disabling Screenshots completely, and one for just stopping to thumbnail them.
In any case, this is an issue with the generator.

**Comment by aleixpol** [comment]
How can we just discard such issues?

If we perpetuate discarding values from the developers whenever they don't fit some random metrics, we won't be able to fix these.
I'd say either take it as an error and don't let the generation proceed or figure out the width/height locally (the generator process _can_ download the image and see the size, if it's so important).

**Comment by ximion** [comment]
The generator should be fixed anyway, this is on my todo list ^^
(generating bad data no matter which flags are set isn't good)
