### ISSUE TITLE
Unclear how to specify license where non-trivial portions of an application is CC-BY-SA licensed

### ISSUE THREAD

**Issue by jadahl** [ximion/appstream#357]
A theoretical example situation:

Lets say we have an application, where the source code is licensed under GPL v3.0+, that bundles part of Wikipedia. Wikipedia licenses its downloaded content under CC-BY-SA 3.0 (Reference: https://en.wikipedia.org/wiki/Wikipedia:Database_download).

Lets also say this application is specifically constructed to be an offline interface to the bundled Wikipedia database. Without the database, it's useless. Thus, a significant part of the application is its database.

Should the project license be GPL v3.0+ *and* CC-BY-SA 3.0? Doing so means it will effectively mark it as proprietary (by e.g. GNOME Software), as creative common licenses are not recognized by opensource.org.

**Comment by jadahl** [comment]
Cc: @pwithnall

**Comment by ximion** [comment]
I do wonder whether AppStream should have its own augmentation to SPDX as to which licenses are considered "free" - since I don't want the AppStream project to become an authority to license questions, maybe adding the ones that are DFSG-free to the mix according to https://wiki.debian.org/DFSGLicenses and other pages will already help and be independent enough. That way we would consider a license as "free software license" if either the FSF, OSI or DFSG says it's free.

**Comment by ximion** [comment]
If SPDX later decides to add that flag, we could drop or own list in AppStream (there seems to be some discussion going on, see https://github.com/spdx/license-list-XML/issues/876 for reference)
