### ISSUE TITLE
Fonts don't appear in the appstream db

### ISSUE THREAD

**Issue by aleixpol** [ximion/appstream#38]
```bash
$ appstreamcli search noto
No component matching 'noto' found.
```

**Comment by ximion** [comment]
On which distro are you running this? Are you sure fonts data actually exists?
(At time, only Fedora ships that data)

**Comment by aleixpol** [comment]
I'm running it on ArchLinux.
Couldn't this be some kind of fallback similar to using .desktop files for applications?

Where's this data? Should it just be adopted in arch?

**Comment by ximion** [comment]
Richard experimented will fallbacks, and the general consensus is that it's not worth the pain at all.
So fonts will need to ship a metainfo file in some way.
As for "should it just be adopted": The `appstream-generator` does not yet fully support this feature, as font-rendering by file is incredibly difficult due to no API being designed for this case.

The next features I will implement in asgen is fonts support and translation-status support (not necessarily in that order, l10n stuff is likely much easier to do - not on Debian though...).
Can you file a feature-request against asgen? If the data is present, AppStream itself handles it correctly here, so I don't think this is a bug in AS.
