### ISSUE TITLE
Some applications are missing on Ubuntu 16.04

### ISSUE THREAD

**Issue by aleixpol** [ximion/appstream#39]
After figuring out the issue #37, now I don't get some applications:
```
$ appstreamcli search kate
Identifier: frescobaldi.desktop [desktop]
Name: Frescobaldi
Summary: LilyPond Music Editor
Package: frescobaldi
Icon: frescobaldi_frescobaldi.png
----
```

**Comment by ximion** [comment]
I am really sorry to have to close this again, but this also is an upstream issue at Ubuntu: http://appstream.ubuntu.com/xenial/universe/issues/kate.html
This appears to be a bug in the old `dep11-generator` that Ubuntu uses for Xenial...
This seems to be resolved with the newer icon-theme and with `appstream-generator` on Debian: https://appstream.debian.org/sid/main/metainfo/kate.html

**Comment by aleixpol** [comment]
Will it be fixed in Ubuntu 16.04?

**Comment by ximion** [comment]
Very good question... The way AppStream works, this can only reliably be fixed by a new upload of kate to xenial-updates, or by making an exception and allowing fresh metadata to enter the stable suite.
I think the latter would be necessary anyway when Ubuntu is switching to asgen, so this would be something to discuss.
But in general: Don't bet on this being fixed in xenial - there is a chance, but it's a huge "maybe".

**Comment by aleixpol** [comment]
There _must_ be something we can do. It works for `gnome-software`.

**Comment by ximion** [comment]
No, it only works for GS if the software is *installed* - uninstall Kate and it will be gone without a way to reinstall it.
