### ISSUE TITLE
platform dependent screenshots

### ISSUE THREAD

**Issue by hsitter** [ximion/appstream#390]
I'd like to suggest to add the ability to tag (<tags>?) screenshots or otherwise constrain them to a given platform. For example Krita, the drawing application, may look different in a plasma environment than in a gnome environment than in a solus environment. To give a more native/integrated feel the authors may choose to offer platform dependent screenshots.

This would incidentally also allow appstream data to feed into the windows and apple stores, which arguably deserve their own set of native screenshots ;)

**Comment by ximion** [comment]
Release artifacts already have a "platform" component, maybe having something like this for screenshots makes sense... With localized screenshots, theme-specific screenshots and all the other stuff people want to specialize screenshots for (who will maintain that properly for each app??), it may make sense to think about how screenshots work as-a-whole. This may even be AppStream 1.0 material, as changing this will be a soft-breaking change.

**Comment by ingokloecker** [comment]
I think this could be solved together with #410. And #304 is also somewhat related.

Regarding the "platform" component of release artifacts, I think this doesn't really match the requirements for screenshots. I would like to have a way to tag screenshots for Windows, Windows Mobile, Android, macOS, iOS and whatever makes sense for Linux (Plasma, Plasma Mobile, Gnome, ...?).

Primarily, the point of the platform tag is not that the store apps could filter the screenshots by platform. The point is that our tooling would only upload those screenshots that are appropriate for a certain store. This is somewhat orthogonal to the purpose of #410 and #304, but not entirely because, for example, Microsoft Store differentiates screenshots for the following device families: Desktop, Mobile, Xbox, Holographic. We don't need to put all of those into the spec, but could allow "arbitrary" values for platform.

"arbitrary" values would allow us to add screenshots for not yet existing platforms to our app data. Stores directly consuming AppStream probably should ignore screenshots for unknown platforms.
