### ISSUE TITLE
[Question] Is it possible to specify the repository by the URI?

### ISSUE THREAD

**Issue by CleoMenezesJr** [ximion/appstream#418]
Today, the center software deal with various repositories. For example: Flatpaks. I can have Flathub, Flathub-beta, GNOME-nightly etc. Is there any way to inform this to Software Center? Something `appstream:io.neovim.nvim/flathub`.

**Comment by JakobDev** [comment]
This is not possible. The idea is to provide the Link to the Suer and the default Software Center will open with the App, no matter what the Installation method is. On most Software centres you can switch between the installation method, if there more than one for a App.

Having a Repo would make no sense. If the User uses Fedora, but you have set Ubuntu as Repo, it will not work. It will also not work, when you set snap as Repo and the System has no Snap.  Even with Flathub, it would only work, when the Repo is added. 

You can also not ensure that Flathub is always available. Some Distros (e.g. elementaryOS) use Flatpaks but have a own Repo.  and Flathub is not available by default. So if a User clicks on a `appstream:org.mozilla.firefox/flathub` link, it will not work, until the User has added the Flathub remote manually. `appstream:org.mozilla.firefox` however will always work, since Firefox is in every Distro Repo. 

Remotes like Flathub Beta, Gnome nightly etc. are not present in any Distro by default and needs to added manually. For Flatpak it would be the best to add a new `flatpak:` URI which also contains a Link to the Repo, so it will work on all Systems that have Flatpak installed. This would also fix the broken Install Button on Flathub.

**Comment by ximion** [comment]
Exactly what @JakobDev said :-)

**Comment by CleoMenezesJr** [comment]
Thx @JakobDev  @ximion 

That's what I thought, but I preferred to ask and clear this doubt.

**Comment by ximion** [comment]
If you have any further questions feel free to ask, and if you have any documentation improvements in mind, feel free to file a PR for it :-)
