### ISSUE TITLE
Add as_license_get_name() API

### ISSUE THREAD

**Issue by pwithnall** [ximion/appstream#423]
For [some functionality we want to implement in gnome-software](https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1626) it would be useful to have an API like:
```
const gchar		*as_license_get_name (const gchar *license_id);
```

It would return a translated string containing the human readable name of the given SPDX license ID.

This would only work for individual license IDs, not SPDX expressions because building a general-purpose translatable string to represent an arbitrary SPDX expression would be hard, and the end result would be very confusing to users (even if it could be perfectly localised).

For the case of a non-trivial SPDX expression, gnome-software will probably use a generic fallback string like “this app is licensed under a combination of free software licenses” or something.

The human-readable name of an SPDX license ID is given by the `name` field in [`licenses.json`](https://github.com/spdx/license-list-data/blob/master/json/licenses.json). Unfortunately it doesn’t look like they provide translated versions, so libappstream would have to carry the translations.

**Comment by wjt** [comment]
There is prior art here.

GtkAboutDialog [translates the names of a list of known licenses](https://gitlab.gnome.org/GNOME/gtk/blob/306276b689c49a9943f251aefcc925338b16e847/gtk/gtkaboutdialog.c#L124-144). Here is Nautilus' About dialog on a French system:

![Capture d’écran de 2023-02-28 14-25-47](https://user-images.githubusercontent.com/86760/221882969-fcfb8741-eb1f-44e9-b130-43d9845b65c3.png)

> Licence publique générale GNU, version 3 ou ultérieure

And here is the _À propos_ dialog of Kdenlive:

![Capture d’écran de 2023-02-28 14-30-30](https://user-images.githubusercontent.com/86760/221883879-7450cd12-b4c7-4398-99d0-f0428c69295d.png)

> License : Version 3 de la License Générale Publique GNU

(I can't help but notice that French GTK calls it the LPG GNU, whereas French KDE calls it LGP GNU. 🤷🏻)

**Comment by ximion** [comment]
You can give `as_get_license_name` a try now! (not sure if the name stays, might become `as_spdx_get_license_name` before 1.0 is released)

This should be in the 1.0 AppStream release soon, and hopefully this implementation is performant enough (if not, we can always use perfect hashsums later if needed).

**Comment by ximion** [comment]
So, I had to partially revert this, as lawyers told me that you don't just simply translate the license name, it's part of the license just as much as the text. So we would need an *official* translation to make this work.

Annoyingly, SPDX embeds stuff that isn't part of the license name itself into the license as well (like "or later"), so, as a compromise the API will now produce translated names for some licenses, but not all.

This is definitely better, especially because some of the licenses have actually names in other languages, like French, and are inherently harder to translate. Of course, the `as_spdx_get_license_name` API stays, so you can use it to get a long-form license name, that just sometimes may not be translated for legal or practical reasons.
