### ISSUE TITLE
Add JSON as Output format for validation

### ISSUE THREAD

**Issue by JakobDev** [ximion/appstream#449]
`appstreamcli validate --format`  lets you choose between 2 different formats: text and yaml. The YAML format is there to be parsed by other programs. I think it would make sense to add a JSON format as well. It should have exactly the same as the YAML, but as JSON. Many programming languages (e.g. Python which is often used for scripts) today already ship with a JSON parser. If you want to parse YAML with these languages, you need a use a extra library. Even if a language ships without a JSON parser, the tooling for JSON is far better than for YAML, because it is more common. So it would be a good idea to add a JSON format.

**Comment by ximion** [comment]
Would be nice, but I don't intend to add a JSON parser or JSON writer dependency to AppStream, and switching libyaml to JSON mode would be quite a pain to implement reliably.
So this feature isn't super likely to be added any time soon...

**Comment by hughsie** [comment]
I think two formats is already _one format too many_ if I'm very honest.

**Comment by ximion** [comment]
Yes... It would be nice to get rod of YAML in favour of something that can be parsed faster (like JSON), but now we're stuck with it.
The validator does have a machine-readable output though, so I see no reason that really prevents it being integrated with existing CI, especially since YAML is ubiquitous in that space already.
