### ISSUE TITLE
Reconsider custom-key-duplicated error

### ISSUE THREAD

**Issue by mcatanzaro** [ximion/appstream#476]
So:

```
$ appstreamcli validate /usr/share/metainfo/org.gnome.Epiphany.appdata.xml 
I: org.gnome.Epiphany.desktop:283: nonstandard-gnome-extension kudos
I: org.gnome.Epiphany.desktop:350: url-not-secure http://www.gnome.org/friends/
E: org.gnome.Epiphany.desktop:360: custom-key-duplicated Purism::form_factor
I: org.gnome.Epiphany.desktop:~: desktop-app-launchable-omitted

✘ Validation failed: errors: 1, infos: 3, pedantic: 2
```

Problem is here:

```
  <custom>
    <value key="Purism::form_factor">workstation</value>
    <value key="Purism::form_factor">mobile</value>
  </custom>
```

Unfortunately this is copy/pasted among lots and lots and lots of different GNOME apps, so... maybe we should downgrade it to not be an error?

There is a better replacement:

```
  <requires>
    <display_length compare="ge">360</display_length>
  </requires>
```

But that does not yet work in practice because Flathub ignores it, and Purism won't be comfortable with removing their metadata before that changes. [This pull request](https://github.com/flatpak/flatpak-builder/pull/517) should fix Flathub, except I suspect Flathub is probably not going to want to land that until this issue is resolved because switching to libappstream now will likely cause apps to disappear.

Anyway, I guess there are really only two options here: downgrade the error to warning, or purge the Purism metadata from all apps that use it. What to do...?

[Downstream issue](https://bugzilla.redhat.com/show_bug.cgi?id=2182874)

**Comment by A6GibKm** [comment]
The problem is that the numbers of apps implementing it is probably in the hundreds, just in my local drive I have over 50. I don't see a way to untangle this mess without downgrading the error to a warning, ideally we remove the custom tag everywhere but this will break anything that was reading the purism tag (e.g. apps.gnome.org or GNOME Software) and the alternative cannot be implemented without https://github.com/flatpak/flatpak-builder/pull/517 which in turn is blocked by the fact that apps will stop compiling due to this issue.

This tag is used *everywhere* in GNOME and I don't think its possible to port everything in just one cycle.

**Comment by mcatanzaro** [comment]
> This tag is used everywhere in GNOME and I don't think its possible to remove the Purism tag everywhere in just one cycle.

Note we do not have one cycle to do this, because these apps are already missing from GNOME Software today (at least in Fedora).

**Comment by mcatanzaro** [comment]
In the absence of guidance to the contrary, I'll start purging Purism metadata from projects I maintain.

**Comment by agx** [comment]
@ximion  (as noted above) I wasn't aware there's plenty of places are relying on this. I had dropped those tags in some projects even. So given that @A6GibKm brought in more examples wouldn't be downgrading to a warning and setting an expiration date (e.g. in 6mo) be more sensible to give projects some time to catch up?

**Comment by ximion** [comment]
> @ximion (as noted above) I wasn't aware there's plenty of places are relying on this. I had dropped those tags in some projects even. So given that @A6GibKm brought in more examples wouldn't be downgrading to a warning and setting an expiration date (e.g. in 6mo) be more sensible to give projects some time to catch up?

It is completely broken behavior though that never once worked as people thought it did... And changing that warning would just hide the error for other users as well, not just in this instance.

This has been broken forever, not just in AppStream, but also in alternative parsers such as appstream-glib.

**Comment by A6GibKm** [comment]
its broken on a technical level, but it certainly works (even if by mistake) otherwise sites as apps.gnome.org would be detecting which apps support mobile devices.

**Comment by agx** [comment]
@ximion it's certainly broken in the sense that duplicate keys don't work so it should be an error when validating. I think all that is asked for here is to not make that an hard error in the validator *right* *now*. 

This would projects give some time to fix things up. Otherwise we're giving people a harder time than they should have - especially on Mobile Linux.

**Comment by mcatanzaro** [comment]
> Note we do not have one cycle to do this, because these apps are already missing from GNOME Software today (at least in Fedora).

This turned out to be not true because Fedora is still using appstream-glib to validate metadata. My app was missing for an unrelated reason (missing icon) that could only be detected by using appstream-util rather than appstreamctl.

This situation of having two different validation tools that trip over different problems is not great.

**Comment by ximion** [comment]
> This situation of having two different validation tools that trip over different problems is not great.

At this point, `appstream-glib` is so incredibly out of date that using `appstream-util` is simply a very bad idea and should not be done since at least 2020. For all intents and purposes, `appstreamcli` should be used as the one tool to verify the metadata (and that's also where any bugs should be fixed in case something isn't validated according to spec).

If you want to find missing icons, use `appstreamcli validate-tree` on an installed directory tree of your app.

**Comment by mcatanzaro** [comment]
Although I agree, please note that Fedora is still using appstream-glib and has no plans to migrate to appstreamcli. So if your metadata fails validation by appstream-glib, your apps will be missing from Fedora's GNOME Software.

**Comment by ximion** [comment]
Why though? Why is Fedora using a dead project while absolutely everyone else moved on?
I'd be willing to help with migrating, but I would first need to know what the issue even is, especially since nobody else seems to have any issue.

It also means, since GNOME Software and Flatpak are using libappstream/appstreamcli, that Fedora is not compatible with the software it ships itself, which is pretty weird.

**Comment by JakobDev** [comment]
> GNOME Software and Flatpak are using libappstream/appstreamcli

Flatpak is still using appstream-glib

**Comment by ximion** [comment]
> Flatpak is still using appstream-glib

It is not: https://github.com/flatpak/flatpak/blob/main/meson.build#L202 & https://github.com/flatpak/flatpak-builder/blob/main/meson.build#L44

**Comment by JakobDev** [comment]
Flatpak itself uses libappstream, but flatpak-builder not. The main branch of flatpak-builder already has the libappstream patch, but it is not in a Release yet. [As you can see here](https://github.com/flathub/org.flatpak.Builder/blob/1a4713682b0761e289f5e1b87f84de033920a61c/org.flatpak.Builder.json#L518), Flathub, which is the main Flatpak repo, is still using a commit of flatpak-builder without libappstream. It was using libappstream for a short time, but this was [reverted](https://github.com/flathub/org.flatpak.Builder/commit/d030f1c4c25d8c3a242e59c03e9ff0651690589b) due to errors. Flathub is also [still using appstream-glib for the validation](https://github.com/flathub/flatpak-builder-lint/blob/b997423a39c77f9a173ba075b9b288a2d1f32f88/flatpak_builder_lint/appstream.py).

**Comment by ximion** [comment]
Yeah, so, Flatpak uses AppStrea, but Flathub not yet would be more correct.
However, apparently all they need to switch is some time to actually do it: https://github.com/flatpak/flatpak-builder/pull/517#issuecomment-1718359614

There are no open issues that I or them are aware of.

**Comment by mcatanzaro** [comment]
> Why though? Why is Fedora using a dead project while absolutely everyone else moved on?
> I'd be willing to help with migrating, but I would first need to know what the issue even is, especially since nobody else seems to have any issue.

[More info here](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/PQGUDGMARGTDMTE6LSKTWGFHD3U3GYCV/)

**Comment by ximion** [comment]
> > Why though? Why is Fedora using a dead project while absolutely everyone else moved on?
> > I'd be willing to help with migrating, but I would first need to know what the issue even is, especially since nobody else seems to have any issue.
> 
> [More info here](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/PQGUDGMARGTDMTE6LSKTWGFHD3U3GYCV/)

For Fedora's main repository where AppStream metadata isn't part of the repository metadata anyway, you could switch to [appstream-generator](https://github.com/ximion/appstream-generator) fairly easily I would think. You would need to port the existing `rpm-md` backend to run a bit better (I could probably help with some of the deprecated XML stuff...) and maybe add some finishing touches to make it integrate better, but that's it.
The tool is also available on Flathub to keep it up-to-date easier: https://flathub.org/apps/org.freedesktop.appstream.generator

The gold standard would be some createrepo integration of course, and for that appstream-generator would be way too fat. That tool could either integrate `appstreamcli compose` with some minor tweaks on the side of ascompose (some advanced features of asgen would be lost, but that might be fine for simpler repos, potentially...) or use libappstream-compose for some more advanced and custom implementation. The compose library does pretty much all of the heavy work behind the scenes anyway.

I don't know Fedora well enough to write this for you, but from afar it doesn't actually look too difficult to make happen.

**Comment by ximion** [comment]
Oh, and appstream-glib is **not** conformant anymore, so that information on the linked mail is outdated. That's why it's [GitHub project website](https://github.com/hughsie/appstream-glib#readme) has a fat warning at the top.

**Comment by ximion** [comment]
Oh, and appstream-glib is **not** conformant anymore, so that information on the linked mail is outdated. That's why its [GitHub project website](https://github.com/hughsie/appstream-glib#readme) has a fat warning at the top.
