### ISSUE TITLE
Documentation doesn't match code

### ISSUE THREAD

**Issue by darkdragon-001** [ximion/appstream#478]
https://github.com/ximion/appstream/blob/9459bdc4322cc8cfcafbfc79386efcf23919fbe9/docs/xml/metainfo-component.xml#L920-L926

doesn't match

https://github.com/ximion/appstream/blob/9459bdc4322cc8cfcafbfc79386efcf23919fbe9/src/as-relation.c#L418-L431

**Comment by ximion** [comment]
This stuff (string names instead of pixel counts for display lengths) will be removed with the 1.0 release anyway, so it's not actually worth bothering too much.

**Comment by JakobDev** [comment]
I still think it's a bad idea to remove the string names. What makes it even worse, is that even it is deprecated `appstremcli validate` still shows no Warning for that.

**Comment by ximion** [comment]
I liked the string names too, but there was a lot of opposition from GNOME designers, and defining them in a sensible way turned out to be much more of a challenge than I though.
We could possibly add a function to AppStream's API to judge the integer values though, for compatibility. Fortunately, the string names are very rarely used right now.

**Comment by ximion** [comment]
This is https://github.com/ximion/appstream/issues/335

**Comment by darkdragon-001** [comment]
I think another problem is with the string values in combination with strong comparison (lt,gt) instead of (le,ge) which will fail just because of a single pixel. Using actual numbers makes this much less likely.
