### ISSUE TITLE
finding appstreamqt finds qt6 when building with qt5

### ISSUE THREAD

**Issue by hsitter** [ximion/appstream#511]
I have an application that does
```
find_package(AppStreamQt REQUIRED)
```
which now seems to find the qt6 version of appstreamqt despite me having written that line for qt5 and the application is also still building for qt5.
Presumably the cmake config name needs versioning or something?

**Comment by ximion** [comment]
This is kind of intentional: AppStream 1.0 is Qt6-only and bumped it's SONAME, so the Qt5 and Qt6 version are coinstallable.
The development headers for both are not however (well... not without some tricks) - so you can either develop with the old 0.16.x series of AppStream and Qt5, or the new (unreleased) AppStream 1.0 series using Qt6 only.

**Comment by ximion** [comment]
Is cmake smart enough to figure this out with this change? Or do I need to rename the package name to `AppStreamQt5` as well, to make the Qt version obvious to cmake?
