### ISSUE TITLE
appstream-compose pre-release order fails at 10 

### ISSUE THREAD

**Issue by ColinKinloch** [ximion/appstream#527]
I'm building a flatpak package (https://github.com/flathub/flathub/pull/4504). The appdata file lists a number of pre-release versions with the version scheme `v0.6~pre14` [furnace.appdata.xml](https://github.com/tildearrow/furnace/blob/b4ca8a3ccfd67d4c48ee1f19b4e9fe5c956a6472/res/furnace.appdata.xml).
When I build it with my host system `flatpak-builder`  (`1.3.3` and `appstream-compose` `0.16.1`) it fails with the error message:
```
org.tildearrow.furnace: AppData problem: tag-invalid : <release> versions are not in order [v0.6~pre10 before v0.6~pre9]
```
However when I build it with the flatpak package `org.flatpak.Builder` which is `flatpak-builder` `1.3.1` and `appstream-compose` `0.15.6` it builds fine.
```
flatpak run org.flatpak.Builder --user --jobs=0 --force-clean --disable-rofiles-fuse --verbose --install ./_build ./org.tildearrow.furnace.yml
```

I've also checked `appstreamcli` and `appstream-util` `vercmp` on both host and flatpak versions and I consistently get `v0.6~pre9 < v0.6~pre10`.

What am I missing? I've tried simplifying the scheme to `0.6.0~pre14` but if fails in the same way.

**Comment by ximion** [comment]
Hi! Unfortunately this is a Flatpak/appstream-glib bug, and is fine in AppStream itself.
See:
```bash
# testing using appstream-glib
$ appstream-util vercmp v0.6~pre9 v0.6~pre10
v0.6~pre9 > v0.6~pre10

# testing using AppStream
$ appstreamcli vercmp v0.6~pre9 v0.6~pre10
v0.6~pre9 << v0.6~pre10
``` 

Flatpak/Flathub was supposed to use appstreamcli already for a while, but the change was reverted due to older clients running into issues (see https://github.com/flatpak/flatpak-builder/pull/517).
However, this is all resolved now, so presumably Flathub could turn this support on again?

I'm afraid you will need to raise this with flatpak-builder/Flathub, as there is nothing either me or you can do about it. Your metadata is perfectly fine, and AppStream is working correctly, it's just flatpak-builder that's currently using an ancient validator with known bugs.

Btw, if you want to know how AppStream compares version numbers, it's currently documented here:
https://www.freedesktop.org/software/appstream/docs/chap-AppStream-Misc.html#sect-AppStream-Misc-VerCmp
(but as said, your data is fine!)

**Comment by sabriunal** [comment]
While testing an appdata I got the following warning. Is these related to this issue.

Tested on:
- Version: 0.16.1 from Fedora
- Version: 0.16.2 from Flathub

```
: org.gnome.tweaks:~: releases-not-in-order 40.0 << 40.beta
   The releases are not sorted in a latest to oldest version order. This is required as some tools
   will assume that the latest version is always at the top. Sorting releases also increases
   overall readability of the metainfo file.
```

```xml
    <release version="40.0" date="2021-03-27">
      <description>
        <p>
            First stable release for GNOME 40. This version is mainly comprised
            of bug fixes and changes for GNOME 40. There are also some notable
            improvements:
        </p>
        <ul>
          <li>Remove Extensions support (now found in the Extensions app)</li>
          <li>Support new font settings for GNOME 40</li>
          <li>Fix UI on small screens</li>
          <li>Update translations</li>
        </ul>
      </description>
    </release>
    <release version="40.beta" date="2021-02-13">
      <description>
        <ul>
          <li>Remove Extensions support</li>
          <li>Add Flatpak support</li>
          <li>Support new font settings</li>
          <li>Fix leaflet on small screens</li>
          <li>Various other bug fixes</li>
          <li>Update translations</li>
        </ul>
      </description>
    </release>

```

**Comment by ximion** [comment]
Yeah, this isn't really fixable - if I change the version comparison algorithm to work for this case, it will break for others.
So you can either ignore this validation (not great either...), or replace `.beta` with `~beta` (better, if your tooling allows that).
