### ISSUE TITLE
NetBSD: POSIX definition removes symlink()

### ISSUE THREAD

**Issue by 0-wiz-0** [ximion/appstream#537]
There are two different philosophies on what `_POSIX_C_SOURCE` is supposed to do.
On Linux it adds stuff to the namespace that is not usually defined; while on Solaris and NetBSD, it removes stuff from the namespace that is not in POSIX.l

For this reason, https://github.com/ximion/appstream/blob/main/meson.build#L132 causes a problem when building on such systems. because on NetBSD it removes `symlink()` from the namespace, causing the build to fail.

Can you please define a different symbol to add whatever this adds for Linux?

**Comment by ximion** [comment]
Sorry, I have no idea how NetBSD works - the POSIX definition was added for compatibility with another BSD back in the day, because before we were building with all GNU extensions.
So, whatever I change now, I'd probably make it worse for someone given that I can't test this properly. Doesn't NetBSD have some kind of compatibility mode that we could use?
Alternatively, one could add a "if NetBSD then do something else" condition to the Meson definition.

**Comment by 0-wiz-0** [comment]
Sorry, this doesn't make sense to me - BSD don't usually have GNU extensions nor need defines for them.
Can we remove it and conditionally add if tor the one where it's needed instead?
