### ISSUE TITLE
Add property about available controls

### ISSUE THREAD

**Issue by hadess** [ximion/appstream#55]
This would be useful for games, to know whether they can be controlled through:
- joystick (maybe with a hint as to which type is best suited)
- keyboard alone
- mouse alone
- mouse + keyboard

See https://mail.gnome.org/archives/games-list/2016-July/thread.html#00002 for the original discussion

**Comment by ximion** [comment]
Sounds good. We can't name this `input_method`, because this word has meaning already.
So, something like
`<input_control>mouse</input_control>`
or
`<input_type>keyboard</input_type>`
I need to think a bit more about the name and whether it makes sense to have a tag with children for this.
@hadess Knowing nothing about joysticks, what does "joystick type" mean?

In any case, I can give this a general thumbs up, but the exact details and tag names would need to be worked out.

**Comment by Kekun** [comment]
@ximion The different controllers could be:
- gamepads
- arcade sticks
- lightguns
- joysticks (for flight simulator)
- steering wheels
- dance mats
- guitars
- …

**Comment by ximion** [comment]
This is resolved via https://github.com/ximion/appstream/pull/265 now. Thank you for reporting this issue!
