### ISSUE TITLE
API assumes there's one of each appstream id

### ISSUE THREAD

**Issue by aleixpol** [ximion/appstream#57]
With the introduction of bundles, it becomes possible to have several versions of the same software available in the system. 

API such as:
```
AsComponent	*as_data_pool_get_component_by_id (AsDataPool *dpool, const gchar *id);
```
Should be returning a list of components. AFAIU.
If we want to have calls to a specific component, we'll have to add more arguments otherwise. If possible.

**Comment by ximion** [comment]
Different versions will always be represented by `AsRelease` lists - but different bundling origins are something different, I am discussing this with @hughsie for a while.
Additionally to the `origin` of a component, we IMHO also need an `origin_type` to determine the bundling system.
I don't know how Snappys "multiple different versions of $stuff" will fit in there, at time this is fundamentally different to how AppStream works - probably the snapd API can solve that by just returning the most recent component / the component whose description should be shown.
In that case, we could get away with `origin_type` (which Richard calls "prefix" because he determines it by special locations files are installed in - I would like to have a more generic and explicit solution).

**Comment by aleixpol** [comment]
Different versions might have different metadata. How is the `AsComponent` built?
