### ISSUE TITLE
relation-display-length-value-invalid unclear

### ISSUE THREAD

**Issue by Alexander-Wilms** [ximion/appstream#572]
https://github.com/RPCS3/rpcs3/blob/03761c5dd45ac5176dd2ba0057154f310ff02ac2/rpcs3/rpcs3.metainfo.xml#L51

contains this line:

`<display_length compare="ge">small</display_length>`

`flatpak run org.freedesktop.appstream.cli validate --pedantic  --explain rpcs3/rpcs3.metainfo.xml`
complains about this, but doesn't explain what shorthand strings are valid.
```
W: net.rpcs3.RPCS3:51: relation-display-length-value-invalid small
   This `display_length` item contains an invalid display length. Its value must either be a
   shorthand string, or positive integer value denoting logical pixels. Please refer to the
   AppStream specification for more information on this tag.
```

However, https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-relations-display_length doesn't mention shorthand strings.

Should one use the value 768, since this is mentioned in the guideline?

Also, the actual check just seems to verify that the value is a positive integer:
https://github.com/ximion/appstream/blob/5612153b704e21ccb4c747b3d6769883d2724024/src/as-validator.c#L1937

**Comment by ximion** [comment]
With AppStream 1.0, the shorthand strings should no longer be used, that's why the metadata is flagged as "needs changes". Using 768 is probably a good guess, have a look at https://blog.tenstral.net/2023/10/how-to-indicate-device-compatibility-for-your-app-in-metainfo-data.html for a bit more details in a more comprehensive form.
Definitely check out `appstreamcli check-syscompat --details`, that's a pretty useful command :-)

**Comment by Alexander-Wilms** [comment]
Fixed in https://github.com/ximion/appstream/commit/0079e0529a5a94bff8f7dc6e77e8f81a738b52cd
