### ISSUE TITLE
core dump on ubuntu 16.04 64bit

### ISSUE THREAD

**Issue by bravomikekilo** [ximion/appstream#58]
When I run the apt update on the ubuntu 16.04 64bit, the appstream get a core dump without push CPU to 100% . To get the update I have to remove the appstream. I already tried the wget way to get 
the new appstream , but it still get core dump . The core dump shows it is a segmention fault
     E: Problem executing scripts APT::Update::Post-Invoke-Success 'if /usr/bin/test -w /var/cache   /app-info -a -e /usr/bin/appstreamcli; then appstreamcli refresh > /dev/null; fi'

**Comment by ximion** [comment]
Does this also happen if you run `appstreamcli refresh-index --force --verbose` manually? If so, is there anything interesting in the output?
A backtrace would also be helpful, ideally install the debug packages for libappstream and appstream in Ubuntu and run the command above under gdb to get one.

This problem is almost certainly solved in Git master, since the cache codepath has been completely reworked. So this is probably more and Ubuntu issue now than an AppStream issue.
(Regardless, finding the issue would still be valuable to patch this in Ubuntu)
Which version of AppStream do you have? (output of `apt list appstream`)

**Comment by bravomikekilo** [comment]
Sorry for the late.
Yes , it core dump at the appstreamcli refresh-index --force --verbose .it even get a core dump when install it with apt install appstream. I wiil work on to get the dump file and A backtrace.

At 2016-08-01 21:52:20, "Matthias Klumpp" <notifications@github.com> wrote:


Does this also happen if you run appstreamcli refresh-index --force --verbose manually? If so, is there anything interesting in the output?
A backtrace would also be helpful, ideally install the debug packages for libappstream and appstream in Ubuntu and run the command above under gdb to get one.

This problem is almost certainly solved in Git master, since the cache codepath has been completely reworked. So this is probably more and Ubuntu issue now than an AppStream issue.
(Regardless, finding the issue would still be valuable to patch this in Ubuntu)
Which version of AppStream do you have? (output of apt list appstream)

**Comment by bravomikekilo** [comment]
I get the dump file 
[core.zip](https://github.com/ximion/appstream/files/395044/core.zip)

**Comment by ximion** [comment]
Which architecture were you running on?
I only got very basic information from the coredump, could you please install the debug symbol packages for appstream and libappstream3 (see https://wiki.ubuntu.com/Debug%20Symbol%20Packages ) and then run the command under gdb and attach the output here?
```
gdb --args "/usr/bin/appstreamcli refresh --force --verbose"
(gdb) run
<wait for it to crash>
(gdb) bt full
```

**Comment by larryprice** [comment]
I was also seeing a core dump on `refresh-index` until I did a `make install` from the master branch yesterday. I'm on Yakkety instead of Xenial.

**Comment by ximion** [comment]
Ah, okay - I had the wrong debug symbols then.
Since the code which was causing this was completely rewritten, whatever the issue was is fixed now in Git master.
As for Ubuntu Yakkety, that should ship with at least the 0.10 release (which I'll probably release tomorrow), so the issue will be fixed there too.
In any other case, please file a bug against Ubuntu so we can track it there.
Thanks for reporting the issue!
