### ISSUE TITLE
Mention tags that allow setting `translate="no"`

### ISSUE THREAD

**Issue by bbhtt** [ximion/appstream#595]
Hi, 

I looked through https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#sect-Metadata-GenericComponent and I can't find which tags support setting `translate="no"`.

It's only mentioned in the code-block for keywords https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-keywords but I assume other translatable tags can have that too.

It'd be nice to have them mentioned somewhere in docs or at least mention that `translate=no` exists.

**Comment by ximion** [comment]
This isn't a feature of the AppStream XML directly, but rather of the ITS rules we provide. So I added a paragraph to the translation quickstart guide, with deals with ITS & Co.
(otherwise people would be confused why `translate="no"` doesn't work if they happen to use some obscure system that doesn't honor our ITS rules).
