### ISSUE TITLE
Provide a clearer error message when validation fails due to not having a untranslated tag

### ISSUE THREAD

**Issue by bbhtt** [ximion/appstream#599]
A big bunch of metainfo files have `xml:lang=en` on Flathub. as-glib was ignoring this but appstreamcli fails.

I'm added a note on docs https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#metainfo-translations

But would be nice if

a) This was properly documented upstream

b) Appstream provided clearer error messages

For example in case of image tags it just says "screenshot-image-source-duplicated" which also happens if you incorrectly put something else in place of `xml:lang` attribute.

It's not really duplicated if the URL is different.

**Comment by bbhtt** [comment]
In case of missing an untranslated tag it says `screenshot-image-source-missing` but the actual error is having only one image tag with the xml:lang attribute

**Comment by ximion** [comment]
This will be hard to address, as there literally is no source image if there isn't a non-translated one. Appstream-glib never supported this properly, so it likely didn't even see this issue.

The `screenshot-image-source-duplicated` is weird though, do you have a testcase for that?
I think we could at most check whether the locale is `en` and then error out in a different way (I don't want to change the explanatory messages, as I'd imagine this to be a fairly rare issue and it would add non-applicable troubleshooting info to all other cases as well and make the message fairly noisy).

Adding that note to the docs was a good call though. How widespread is this issue? I haven't seen it in any significant quantity in the Debian archive (but I will check again tomorrow).

**Comment by ximion** [comment]
> Here, the issue is using `xml=$lang` instead of `xml:lang="$lang"`

There is no way we can detect that unless we also validate every single XML attribute... - and error out if there are any unknown ones. From AppStream's perspective, there are two tags while only one was allowed, so that's why the warning is thrown.



> > I think we could at most check whether the locale is en and then error out in a different way
> 
> Yea I think that'd be fine too.

It just occurred to me that we can't actually do that, because as crazy as it sounds, translations from the "source locale" to English would actually be permitted... (it's a bit of a weird case, translations to `en-GB` would make more sense, to make them British-ish).

We could probably check for this though to refine the issue tag. I'll look into this.

> There's apps repeating it too
> 
> https://github.com/flathub/org.gtk.Gtk3theme.Greybird-dark/blob/0762a232ad82731f6c39714bb3020e171940ccd3/org.gtk.Gtk3theme.Greybird-dark.appdata.xml#L6-L7

This should actually validate just fine, as there is an untranslated and a translated tag - we just store duplicated information, which makes no sense, but it's a technically correct file.

> https://github.com/flathub/io.github.dman95.SASM/blob/5a54d4ec0ec477047dd9eeec0f1d043fc5be975a/patches/0001-Deduplicate-Linux-and-BSD-into-Unix.patch#L2673

This file is bad for completely different reasons, the `description` tag is translated wrong. The validator will flag that as well.

Overall, AppStream has a much more extensive set of checks than appstream-util had, and it will even validate the newer tags that appstream-glib didn't know yet. So I guess there will be a bit of adjustment going on :-)
But that's definitely a good thing! That SASM metadata is completely broken as-is and the translation will never be shown if parsed - or we will only get the Russian localization (I'll have to check what the parser does in this case).
