### ISSUE TITLE
translatable=no support for metainfo files

### ISSUE THREAD

**Issue by yakushabb** [ximion/appstream#623]
I'm not an expert on gettext or GTK-related topics, but I've noticed that several apps use translatable properties to mark UI strings as either translatable or not.

For example:
```
<property name="tooltip-text" translatable="yes">Copy</property>
<property name="title" translatable="no">PNG</property>
```

It appears that the metainfo files only support the `translate="no"` property:

> One special case is the description block in MetaInfo files and release metadata. In MetaInfo files, each individual paragraph of a description (or enumerated entry) is translated individually, however, you can only exclude the complete block from being translated by adding `translate="no"` to the description element.

(Source: https://freedesktop.org/software/appstream/docs/sect-Quickstart-Translation.html)

I believe the usage of `<description translatable="no">` is already accepted and used by many projects, as evident from GitHub repositories:

https://github.com/search?q=description+translatable%3D%22no%22+language%3AXML&type=code&l=XML

My assumptions are:
- The `<description translatable="no">` usage is already accepted by many developers.
- The `<description translatable="no">` usage is also well established across UI files.
- Changing `translatable="no"` to `translate="no"` offers no advantage for developers.
- Changing this usage may require additional changes for developers and translation platforms.

My suggestion:
- Developers could continue to use `translatable="no"`."

**Comment by ximion** [comment]
I will not change this. It would be a breaking change, which is absolutely not okay, and supporting both would give us no benefit other than an internal inconsistency in the AppStream specification with confused users as a result, in addition to making the implementation harder as well (as we would have to support both properties everywhere).

There is also no convention or standard for this anywhere.

AppStream uses imperative properties (`scale`, `compare` instead of `scaling`, `comparison`) for these kinds of things, which is why `translate` is also named the way it is.

Which leaves the GitHub search, which puzzled me a bit. Looks like that's due to the older appstream-glib project implementing something else, which is a bit unfortunate - but I think adding even more confusion by allowing more stuff in AppStream proper will actually make this situation worse, so I firmly believe it's a bad idea.
(fortunately that search picked up a ton of things that aren't metainfo files, so it's likely not was widespread as it first appears)

**Comment by yakushabb** [comment]
Thanks for answer. I will try to correct some projects that I have relations.

**Comment by ximion** [comment]
Thank you, that would help a lot! Updating xgettext to include the latest `metainfo.its` from this project would also be useful. I files a PR in the past, but meanwhile years later that one will already be out of date.
I'll have a look into that.
(updating xgettext would mean that this translation works even in `appstream` is not installed when the strings are extracted/joined).

**Comment by yakushabb** [comment]
Is it possible to include information or warnings about `translatable="no"` strings in appstreamcli?

Some developers might recognize the problem and fix it before it's reported by translators.

**Comment by ximion** [comment]
> Is it possible to include information or warnings about `translatable="no"` strings in appstreamcli?
> 
> Some developers might recognize the problem and fix it before it's reported by translators.

That's definitely something we can do. Patches welcome! (I will have a look at it, but probably not immediately)
