### ISSUE TITLE
developer element not translatable

### ISSUE THREAD

**Issue by AsciiWolf** [ximion/appstream#639]
The developer element is marked as not translatable [here](https://github.com/ximion/appstream/blob/6efe972ff5ec573fa7705de0c1c67b04f6e99aba/data/its/metainfo.its#L32) (added by [this commit](https://github.com/ximion/appstream/commit/6292398f2271a0aa7ed9f7dd47f1faf5b9969960)) although the [AppStream specification states](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-developer) that this element (name, not the id) should be translatable.

I have stumbled upon this when translating some GNOME projects and wondering why the developer string is not available for translation anymore in them.

**Comment by ximion** [comment]
You are misreading that commit. The change just allows people to mark the `name` as non-translatable, it is translated by default (as the prior rule is taken in that case if no `translate` property exists).

So, that is definitely not the issue. You say the name tag did translate before? Usually these issues happen because someone uninstalls AppStream and xgettext falls back to the default files, which do not include certain new tags.

Gettext is super slow with releases ass well, so even when submitting a patch it takes a while for changes to take effect. But I guess I should send them a patch to bring their copy of the ITS rules up to the ones we ship upstream.

**Comment by AsciiWolf** [comment]
You're right. Sorry!

**Comment by yakushabb** [comment]
No answer from any gettext developer.

https://lists.gnu.org/archive/html/bug-gettext/2024-04/msg00000.html
