### ISSUE TITLE
Document how to use the bundle tag

### ISSUE THREAD

**Issue by probonopd** [ximion/appstream#69]
Thanks for adding the bundle tag and for adding [AppImage](http://appimage.org/) support.

Please document the best practices for how the bundle tag should be used. I try to summarize what I understood from our earlier conversation, feel free to correct me:

- The bundle tag is __not__  supposed to be added to `usr/share/metainfo/$ID.appdata.xml` files but is added to collection data (a.k.a. distro metadata) by a compose server (e.g., operated by a distribution or app store). If upstream adds the bundle tag to `usr/share/metainfo/$ID.appdata.xml` anyway it is likely to be removed by the compose server
- The compose server has to get the information from upstream. Upstream can submit it to the compose server by either placing a file in a special format (still to be defined) into a upstream-provided directory; or by using an upload tool (still to be written) that submits the data to the compose server; or by manually enter the information into a web interface of the compose server (to be written)
- It is not allowed to have sub-tags inside the `<bundle>` tag. This is to allow for easier verification and deserialization. But it is possible to have more than one `<bundle>` tag, even for the same bundling format (this is useful when an upstream wants to provide different channels like stable, weekly, daily, continuous, canary, aurora, etc.)

**Comment by ximion** [comment]
All the assumptions are correct, and everything is actually documented.
If the `<bundle/>` tag was allowed in metainfo files, you would find it in [its documentation](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#sect-Metadata-GenericComponent). How the compose server gets its information to build the final metadata is not something which should be in the spec, as it is an implementation detail. The spec makes suggestions for some obvious cases though (e.g. "take it from a .desktop file").

The bundle tag is described [in the spec](https://www.freedesktop.org/software/appstream/docs/chap-CollectionData.html#tag-ct-bundle) as having a string value, so of course no subtags are possible. And allowing it to be defined multiple times for different bundling systems is also mentioned there.

What is not mentioned is to define it for different "channels", because this concept doesn't exist in AppStream yet and needs some discussion first whether we add it and how it will look like then.

**Comment by probonopd** [comment]
Thanks for the clarification.
