### ISSUE TITLE
Database is not found

### ISSUE THREAD

**Issue by aleixpol** [ximion/appstream#7]
Recently it was changed to look for the database in `/default` instead of `/C`. This breaks on my system. Reverting the commit `9426db0a96b24fdcc85c895cc97a1a18699620d7` fixed the issue for me.

Maybe because I'm not running appstream-glib master?
```AppStream CLI tool version: 0.8.5```

**Comment by ximion** [comment]
appstream-glib has nothing to do with this (in case you mean hughsie's project, and not libappstream) :-)
But a `sudo appstreamcli refresh --force` should fix this issue for you.
The reason for changing the database location is that I am currently doing some major refactoring on the cache. The Qt library should check for the cache version first before loading the cache, but since it doesn't, people combining an older version of the Qt library with the new database will run into heavy troubles.
The next release will correct that issue for the future, and also move the database to avoid the issue mentioned above (also, "default" is a much better name than "C", since "C" is a locale value already, which might hurt a little in case we decide to build multiple per-language caches later).
Btw, glad that you noticed changes! I wanted to give you a heads up for the changes on IRC anyway (couldn't find you at the WE), and since the refactoring will likely be complete for the Qt library as well by tonight, it would be cool if you could check that I didn't break anything (unittests for the Qt library would be even cooler, but that's a bit trickier to realize).
