### ISSUE TITLE
AppStream::Pool::load() returns false on some systems

### ISSUE THREAD

**Issue by aleixpol** [ximion/appstream#97]
At least OpenSuse, Neon and Kubuntu (with PPAs).

Reference: https://bugs.kde.org/show_bug.cgi?id=374279

**Comment by ximion** [comment]
That is expected behavior, it will return `TRUE` only if *all* data was loaded, if only one bit of data was ignored, `FALSE` is returned.
To check if there was a bigger error, the function will set a `GError` - we should expose the error message too on the Qt bindings (add a `lastError` QString property? or do something more fancy?).

Changing the meaning of the `load()` return value could break things, doing so would only make sense with some prior announcement (it would at least break appstreamcli, which uses it to show a warning message (but no hard failure) if data wasn't loaded. The function returning false is usually a hint for more experienced users to search for issues, non-technically advanced users should ignore it, since the issues is almost always in upstream software or an issue with the distributor)
